(define (make-point x y)
 (cons x y))
(define (x-point p)
 (car p))
(define (y-point p)
 (cdr p))
(define (make-segment start end)
 (cons start end))
(define (start-segment segment)
 (car segment))
(define (end-segment segment)
 (cdr segment))
(define (midpoint-segment segment)
 (make-point (/ (+ (x-point (start-segment segment)) (x-point (end-segment segment))) 2) (/ (+ (y-point (start-segment segment)) (y-point (end-segment segment))) 2)))

(define (print-point p)
 (print (x-point p) " " (y-point p)))

(print-point (make-point 1 2))

(print-point (midpoint-segment (make-segment (make-point 1 2) (make-point 3 4))))
